name: Test Workflow

on:
  pull_request

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: test docker-run action
      uses: ./
      with:
        params: |
          echo INSIDE && cat /etc/os-release && ls -alF
